# Phillies Data Wrangling

In [1]:
import pandas as pd
import numpy as np
import folium

## Import Data Sets

In [2]:
philly_stops = pd.read_csv("../data/PHILLY_STOPS_DATA_WITH_GAME_INDICATORS.csv")

/var/folders/k9/6ttfwb0s7ssb63rlmgdbybc80000gn/T/ipykernel_3373/2849353646.py:1: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  philly_stops = pd.read_csv("../data/PHILLY_STOPS_DATA_WITH_GAME_INDICATORS.csv")

In [3]:
philly_stops

,raw_row_number,date,time,location,lat,lng,district,service_area,subject_age,subject_race,...,raw_individual_contraband,raw_vehicle_contraband,eagles_home_game,eagles_away_game,76ers_home_game,76ers_away_game,phillies_home_game,phillies_away_game,flyers_home_game,flyers_away_game
0,411981,2014-01-01,01:14:00,NaN,NaN,NaN,19.0,191,31.0,black,...,True,False,False,False,True,False,False,False,False,False
1,407442,2014-01-01,01:57:00,NaN,NaN,NaN,12.0,121,21.0,black,...,False,False,False,False,True,False,False,False,False,False
2,217556,2014-01-01,03:30:00,3400 BLOCK SPRUCE ST,39.950424,-75.192680,18.0,183,24.0,black,...,False,False,False,False,True,False,False,False,False,False
3,217557,2014-01-01,03:40:00,3400 BLOCK SPRUCE ST,39.950424,-75.192680,18.0,183,20.0,black,...,False,False,False,False,True,False,False,False,False,False
4,230988,2014-01-01,08:30:00,N 56TH ST / UPLAND WAY,39.983712,-75.234188,19.0,193,31.0,black,...,False,False,False,False,True,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1865091,1791698,2018-04-14,21:36:00,S 59TH ST / ELMWOOD AV,39.928084,-75.221956,12.0,123,60.0,black,...,False,False,False,False,False,False,True,False,False,False
1865092,1789312,2018-04-14,22:01:00,2600 BLOCK JUDSON ST,39.998242,-75.175190,39.0,393,33.0,asian/pacific islander,...,False,False,False,False,False,False,True,False,False,False
1865093,1791237,2018-04-14,22:48:00,500 BLOCK E OLNEY AV,40.033812,-75.114429,35.0,352,21.0,black,...,False,False,False,False,False,False,True,False,False,False
1865094,1791243,2018-04-14,22:48:00,500 BLOCK E OLNEY AV,40.033812,-75.114429,35.0,352,22.0,black,...,False,False,False,False,False,False,True,False,False,False
1865095,1791232,2018-04-14,23:10:00,200 BLOCK W LEHIGH AV,39.991461,-75.134880,25.0,253,69.0,black,...,False,False,False,False,False,False,True,False,False,False

In [4]:
phillies = pd.read_csv("../data/cleanedPhilliesData.csv")
phillies

,Game,Day,Date,StartTime,LOG,EndTime,DayGame,Rank,CLI,Home,...,TeamScore,OppScore,PointDiff,Win,Walkoff,Season,Streak,Rivalry,Mets,Braves
0,1,Monday,2014-03-31,14:05:00,216,17:41:00,1,1,0.96,1,...,14,10,4,1,0,2014,1,0,0,0
1,2,Tuesday,2014-04-01,20:05:00,194,23:19:00,0,3,0.98,1,...,2,3,-1,0,1,2014,-1,0,0,0
2,3,Wednesday,2014-04-02,20:05:00,182,23:07:00,0,4,0.88,1,...,3,4,-1,0,1,2014,-2,0,0,0
3,4,Friday,2014-04-04,14:20:00,196,17:36:00,1,4,0.88,1,...,7,2,5,1,0,2014,1,0,0,0
4,5,Saturday,2014-04-05,14:20:00,173,17:13:00,1,3,0.92,1,...,2,0,2,1,0,2014,2,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
806,158,Wednesday,2018-09-26,20:40:00,171,23:31:00,0,3,0.00,1,...,0,14,-14,0,0,2018,-7,0,0,0
807,159,Thursday,2018-09-27,15:10:00,186,18:16:00,1,3,0.00,1,...,3,5,-2,0,0,2018,-8,0,0,0
808,160,Friday,2018-09-28,19:05:00,222,22:47:00,0,3,0.00,0,...,2,10,-8,0,0,2018,-9,1,0,1
809,161,Saturday,2018-09-29,19:05:00,163,21:48:00,0,3,0.00,0,...,3,0,3,1,0,2018,1,1,0,1
810,162,Sunday,2018-09-30,15:05:00,177,18:02:00,1,3,0.00,0,...,3,1,2,1,0,2018,2,1,0,1

In [5]:
phillies.columns

Index(['Game', 'Day', 'Date', 'StartTime', 'LOG', 'EndTime', 'DayGame', 'Rank',
       'CLI', 'Home', 'Attendance', 'Opp', 'TeamScore', 'OppScore',
       'PointDiff', 'Win', 'Walkoff', 'Season', 'Streak', 'Rivalry', 'Mets',
       'Braves'],
      dtype='object')

In [6]:
philly_stops.columns

Index(['raw_row_number', 'date', 'time', 'location', 'lat', 'lng', 'district',
       'service_area', 'subject_age', 'subject_race', 'subject_sex', 'type',
       'arrest_made', 'outcome', 'contraband_found', 'frisk_performed',
       'search_conducted', 'search_person', 'search_vehicle', 'raw_race',
       'raw_individual_contraband', 'raw_vehicle_contraband',
       'eagles_home_game', 'eagles_away_game', '76ers_home_game',
       '76ers_away_game', 'phillies_home_game', 'phillies_away_game',
       'flyers_home_game', 'flyers_away_game'],
      dtype='object')

## Parse Date columns

In [7]:
philly_stops['date'] = pd.to_datetime(philly_stops['date'], format='mixed', errors='coerce').dt.date

In [8]:
phillies['Date'] = pd.to_datetime(phillies['Date']).dt.date

# Remove dates that occur after the end of the stop data
max_date = philly_stops['date'].max()
phillies = phillies[phillies['Date'] <= max_date]

phillies['Date']

0      2014-03-31
1      2014-04-01
2      2014-04-02
3      2014-04-04
4      2014-04-05
          ...
656    2018-04-09
657    2018-04-10
658    2018-04-11
659    2018-04-13
660    2018-04-14
Name: Date, Length: 661, dtype: object

In [9]:
philly_stops = philly_stops.dropna(subset=['date'])

In [10]:
philly_stops['date']

0          2014-01-01
1          2014-01-01
2          2014-01-01
3          2014-01-01
4          2014-01-01
              ...
1865091    2018-04-14
1865092    2018-04-14
1865093    2018-04-14
1865094    2018-04-14
1865095    2018-04-14
Name: date, Length: 1865096, dtype: object

## Create square regions

### Drop unnecessary columns

In [11]:
philly_stops.drop(columns=['raw_row_number', 'location', 'district',
       'service_area', 'subject_age', 'subject_race', 'subject_sex', 'type',
       'arrest_made', 'outcome', 'contraband_found', 'frisk_performed',
       'search_conducted', 'search_person', 'search_vehicle', 'raw_race',
       'raw_individual_contraband', 'raw_vehicle_contraband'], inplace=True)
philly_stops.columns

Index(['date', 'time', 'lat', 'lng', 'eagles_home_game', 'eagles_away_game',
       '76ers_home_game', '76ers_away_game', 'phillies_home_game',
       'phillies_away_game', 'flyers_home_game', 'flyers_away_game'],
      dtype='object')

### Remove NA value rows

In [12]:
# Check % of na values first
print(philly_stops.isna().mean() * 100)

philly_stops = philly_stops.dropna()
philly_stops

date                  0.000000
time                  0.000000
lat                   5.613491
lng                   5.613491
eagles_home_game      0.000000
eagles_away_game      0.000000
76ers_home_game       0.000000
76ers_away_game       0.000000
phillies_home_game    0.000000
phillies_away_game    0.000000
flyers_home_game      0.000000
flyers_away_game      0.000000
dtype: float64

,date,time,lat,lng,eagles_home_game,eagles_away_game,76ers_home_game,76ers_away_game,phillies_home_game,phillies_away_game,flyers_home_game,flyers_away_game
2,2014-01-01,03:30:00,39.950424,-75.192680,False,False,True,False,False,False,False,False
3,2014-01-01,03:40:00,39.950424,-75.192680,False,False,True,False,False,False,False,False
4,2014-01-01,08:30:00,39.983712,-75.234188,False,False,True,False,False,False,False,False
5,2014-01-01,08:53:00,39.953124,-75.181936,False,False,True,False,False,False,False,False
6,2014-01-01,09:00:00,39.989757,-75.229019,False,False,True,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
1865091,2018-04-14,21:36:00,39.928084,-75.221956,False,False,False,False,True,False,False,False
1865092,2018-04-14,22:01:00,39.998242,-75.175190,False,False,False,False,True,False,False,False
1865093,2018-04-14,22:48:00,40.033812,-75.114429,False,False,False,False,True,False,False,False
1865094,2018-04-14,22:48:00,40.033812,-75.114429,False,False,False,False,True,False,False,False
1865095,2018-04-14,23:10:00,39.991461,-75.134880,False,False,False,False,True,False,False,False

### Convert latitude and longitude to Km based coordinates and create 1 km square grid

In [13]:
km_to_deg_lat = 1 / 111
mean_lat = philly_stops['lat'].mean()

# Longitude conversion depends on latitude
km_to_deg_lng = 1 / (111 * np.cos(np.radians(mean_lat)))

# Bin each point the floor km
philly_stops['lat_bin'] = np.floor(philly_stops['lat'] / km_to_deg_lat)
philly_stops['lng_bin'] = np.floor(philly_stops['lng'] / km_to_deg_lng)

# Create a region ID
philly_stops['region'] = philly_stops['lat_bin'].astype(int).astype(str) + "_" + philly_stops['lng_bin'].astype(int).astype(str)

print(philly_stops[['lat', 'lng', 'region']].head())

         lat        lng      region
2  39.950424 -75.192680  4434_-6395
3  39.950424 -75.192680  4434_-6395
4  39.983712 -75.234188  4438_-6399
5  39.953124 -75.181936  4434_-6394
6  39.989757 -75.229019  4438_-6398

### Plot grid on a map

In [14]:
# Center map
center_lat = philly_stops['lat'].mean()
center_lng = philly_stops['lng'].mean()

m = folium.Map(location=[center_lat, center_lng], zoom_start=11)

# Get unique grid cells
unique_cells = philly_stops[['lat_bin', 'lng_bin']].drop_duplicates()

for _, row in unique_cells.iterrows():
    lat_bin = row['lat_bin']
    lng_bin = row['lng_bin']

    # Convert back to coordinates (bottom-left corner)
    lat_min = lat_bin * km_to_deg_lat
    lng_min = lng_bin * km_to_deg_lng

    lat_max = lat_min + km_to_deg_lat
    lng_max = lng_min + km_to_deg_lng

    # Draw rectangle
    folium.Rectangle(
        bounds=[[lat_min, lng_min], [lat_max, lng_max]],
        color='blue',
        weight=1,
        fill=False
    ).add_to(m)

m

In [15]:
philly_stops

,date,time,lat,lng,eagles_home_game,eagles_away_game,76ers_home_game,76ers_away_game,phillies_home_game,phillies_away_game,flyers_home_game,flyers_away_game,lat_bin,lng_bin,region
2,2014-01-01,03:30:00,39.950424,-75.192680,False,False,True,False,False,False,False,False,4434.0,-6395.0,4434_-6395
3,2014-01-01,03:40:00,39.950424,-75.192680,False,False,True,False,False,False,False,False,4434.0,-6395.0,4434_-6395
4,2014-01-01,08:30:00,39.983712,-75.234188,False,False,True,False,False,False,False,False,4438.0,-6399.0,4438_-6399
5,2014-01-01,08:53:00,39.953124,-75.181936,False,False,True,False,False,False,False,False,4434.0,-6394.0,4434_-6394
6,2014-01-01,09:00:00,39.989757,-75.229019,False,False,True,False,False,False,False,False,4438.0,-6398.0,4438_-6398
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1865091,2018-04-14,21:36:00,39.928084,-75.221956,False,False,False,False,True,False,False,False,4432.0,-6398.0,4432_-6398
1865092,2018-04-14,22:01:00,39.998242,-75.175190,False,False,False,False,True,False,False,False,4439.0,-6394.0,4439_-6394
1865093,2018-04-14,22:48:00,40.033812,-75.114429,False,False,False,False,True,False,False,False,4443.0,-6388.0,4443_-6388
1865094,2018-04-14,22:48:00,40.033812,-75.114429,False,False,False,False,True,False,False,False,4443.0,-6388.0,4443_-6388
1865095,2018-04-14,23:10:00,39.991461,-75.134880,False,False,False,False,True,False,False,False,4439.0,-6390.0,4439_-6390

### Drop extra location columns

In [16]:
philly_stops.drop(columns=['lat', 'lng'], inplace=True)
philly_stops

,date,time,eagles_home_game,eagles_away_game,76ers_home_game,76ers_away_game,phillies_home_game,phillies_away_game,flyers_home_game,flyers_away_game,lat_bin,lng_bin,region
2,2014-01-01,03:30:00,False,False,True,False,False,False,False,False,4434.0,-6395.0,4434_-6395
3,2014-01-01,03:40:00,False,False,True,False,False,False,False,False,4434.0,-6395.0,4434_-6395
4,2014-01-01,08:30:00,False,False,True,False,False,False,False,False,4438.0,-6399.0,4438_-6399
5,2014-01-01,08:53:00,False,False,True,False,False,False,False,False,4434.0,-6394.0,4434_-6394
6,2014-01-01,09:00:00,False,False,True,False,False,False,False,False,4438.0,-6398.0,4438_-6398
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1865091,2018-04-14,21:36:00,False,False,False,False,True,False,False,False,4432.0,-6398.0,4432_-6398
1865092,2018-04-14,22:01:00,False,False,False,False,True,False,False,False,4439.0,-6394.0,4439_-6394
1865093,2018-04-14,22:48:00,False,False,False,False,True,False,False,False,4443.0,-6388.0,4443_-6388
1865094,2018-04-14,22:48:00,False,False,False,False,True,False,False,False,4443.0,-6388.0,4443_-6388
1865095,2018-04-14,23:10:00,False,False,False,False,True,False,False,False,4439.0,-6390.0,4439_-6390

## Aggregate stops by date, region, and hour

### Convert time to hour block

In [17]:
philly_stops['hour'] = pd.to_datetime(philly_stops['time'], format='%H:%M:%S').dt.hour
philly_stops.head()

,date,time,eagles_home_game,eagles_away_game,76ers_home_game,76ers_away_game,phillies_home_game,phillies_away_game,flyers_home_game,flyers_away_game,lat_bin,lng_bin,region,hour
2,2014-01-01,03:30:00,False,False,True,False,False,False,False,False,4434.0,-6395.0,4434_-6395,3
3,2014-01-01,03:40:00,False,False,True,False,False,False,False,False,4434.0,-6395.0,4434_-6395,3
4,2014-01-01,08:30:00,False,False,True,False,False,False,False,False,4438.0,-6399.0,4438_-6399,8
5,2014-01-01,08:53:00,False,False,True,False,False,False,False,False,4434.0,-6394.0,4434_-6394,8
6,2014-01-01,09:00:00,False,False,True,False,False,False,False,False,4438.0,-6398.0,4438_-6398,9

In [18]:
# Drop time column
philly_stops.drop(columns=['time'], inplace=True)
philly_stops.head()

,date,eagles_home_game,eagles_away_game,76ers_home_game,76ers_away_game,phillies_home_game,phillies_away_game,flyers_home_game,flyers_away_game,lat_bin,lng_bin,region,hour
2,2014-01-01,False,False,True,False,False,False,False,False,4434.0,-6395.0,4434_-6395,3
3,2014-01-01,False,False,True,False,False,False,False,False,4434.0,-6395.0,4434_-6395,3
4,2014-01-01,False,False,True,False,False,False,False,False,4438.0,-6399.0,4438_-6399,8
5,2014-01-01,False,False,True,False,False,False,False,False,4434.0,-6394.0,4434_-6394,8
6,2014-01-01,False,False,True,False,False,False,False,False,4438.0,-6398.0,4438_-6398,9

### Aggregate (count) the number of stops for each date, region, hour combination

In [19]:
aggregate_philly_stops = (
    philly_stops
    .groupby(['date', 'hour', 'region'])
    .size()
    .reset_index(name='stop_count')
)

aggregate_philly_stops

               date  hour      region  stop_count
0        2014-01-01     3  4434_-6395           2
1        2014-01-01     8  4434_-6394           1
2        2014-01-01     8  4438_-6399           1
3        2014-01-01     9  4435_-6398           1
4        2014-01-01     9  4436_-6399           1
...             ...   ...         ...         ...
1087112  2018-04-14    21  4446_-6393           1
1087113  2018-04-14    21  4446_-6394           1
1087114  2018-04-14    22  4439_-6394           1
1087115  2018-04-14    22  4443_-6388           2
1087116  2018-04-14    23  4439_-6390           1

[1087117 rows x 4 columns]

## Fill 0 stops for any missing combinations

In [20]:
# Create full date range
all_dates = pd.date_range(start=aggregate_philly_stops['date'].min(), end=aggregate_philly_stops['date'].max(), freq='D')

# Define full hour range (0-23)
all_hours = range(0, 24)

# Get all regions
all_regions = aggregate_philly_stops['region'].unique()

# Create full combination grid
full_index = pd.MultiIndex.from_product(
    [all_dates, all_hours, all_regions],
    names=['date', 'hour', 'region']
)

# Reindex
aggregate_philly_stops = (
    aggregate_philly_stops.set_index(['date', 'hour', 'region'])
      .reindex(full_index)
      .reset_index()
)

# Fill missing values with 0 stops
aggregate_philly_stops['stop_count'] = aggregate_philly_stops['stop_count'].fillna(0).astype(int)
aggregate_philly_stops['date'] = pd.to_datetime(aggregate_philly_stops['date']).dt.date
aggregate_philly_stops

                date  hour      region  stop_count
0         2014-01-01     0  4434_-6395           0
1         2014-01-01     0  4434_-6394           0
2         2014-01-01     0  4438_-6399           0
3         2014-01-01     0  4435_-6398           0
4         2014-01-01     0  4436_-6399           0
...              ...   ...         ...         ...
15099115  2018-04-14    23  4427_-6392           0
15099116  2018-04-14    23  4450_-6397           0
15099117  2018-04-14    23  4449_-6396           0
15099118  2018-04-14    23  4446_-6401           0
15099119  2018-04-14    23  4445_-6401           0

[15099120 rows x 4 columns]

### Rejoin with home/away labels

In [21]:
# Get the home/away labels for each date
date_level_data = (
    philly_stops
    .drop_duplicates(subset=['date'])
    .drop(['region', 'hour', 'lat_bin', 'lng_bin'], axis=1)
)

# merge home/away info with aggregated data
aggregate_philly_stops = aggregate_philly_stops.merge(
    date_level_data,
    on='date',
    how='left'
)

# Fill NA home/away days with False
game_cols = [
    'eagles_home_game', 'eagles_away_game',
    '76ers_home_game', '76ers_away_game',
    'phillies_home_game', 'phillies_away_game',
    'flyers_home_game', 'flyers_away_game'
]

aggregate_philly_stops[game_cols] = (
    aggregate_philly_stops[game_cols]
    .fillna(False)
)

aggregate_philly_stops

/var/folders/k9/6ttfwb0s7ssb63rlmgdbybc80000gn/T/ipykernel_3373/291257668.py:25: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  .fillna(False)

,date,hour,region,stop_count,eagles_home_game,eagles_away_game,76ers_home_game,76ers_away_game,phillies_home_game,phillies_away_game,flyers_home_game,flyers_away_game
0,2014-01-01,0,4434_-6395,0,False,False,True,False,False,False,False,False
1,2014-01-01,0,4434_-6394,0,False,False,True,False,False,False,False,False
2,2014-01-01,0,4438_-6399,0,False,False,True,False,False,False,False,False
3,2014-01-01,0,4435_-6398,0,False,False,True,False,False,False,False,False
4,2014-01-01,0,4436_-6399,0,False,False,True,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
15099115,2018-04-14,23,4427_-6392,0,False,False,False,False,True,False,False,False
15099116,2018-04-14,23,4450_-6397,0,False,False,False,False,True,False,False,False
15099117,2018-04-14,23,4449_-6396,0,False,False,False,False,True,False,False,False
15099118,2018-04-14,23,4446_-6401,0,False,False,False,False,True,False,False,False
15099119,2018-04-14,23,4445_-6401,0,False,False,False,False,True,False,False,False

### Calculate Expected number of rows for verification

In [22]:
len(all_dates)*len(all_hours)*len(all_regions)

15099120

## Add game information and home game flag to stop data

### First, check that all gamedays are in the stop data

In [23]:
missing_dates = phillies.loc[~phillies['Date'].isin(aggregate_philly_stops['date']), 'Date']

# Print any dates that are missing from the stop data
missing_dates

Series([], Name: Date, dtype: object)

 ### Left join philly stops with Phillies data

In [24]:
aggregate_philly_stops.columns

Index(['date', 'hour', 'region', 'stop_count', 'eagles_home_game',
       'eagles_away_game', '76ers_home_game', '76ers_away_game',
       'phillies_home_game', 'phillies_away_game', 'flyers_home_game',
       'flyers_away_game'],
      dtype='object')

In [25]:
phillies.columns

Index(['Game', 'Day', 'Date', 'StartTime', 'LOG', 'EndTime', 'DayGame', 'Rank',
       'CLI', 'Home', 'Attendance', 'Opp', 'TeamScore', 'OppScore',
       'PointDiff', 'Win', 'Walkoff', 'Season', 'Streak', 'Rivalry', 'Mets',
       'Braves'],
      dtype='object')

In [26]:
# Merge (left join keeps all philly_stops rows)
# non-gamedays will have NA in all Phillies columns
merged_df = aggregate_philly_stops.merge(
    phillies,
    how='left',
    left_on='date',
    right_on='Date'
)

In [27]:
# Check that all gamedays are in the final dataset.
print(merged_df['Date'].nunique())

# Drop the Phillies date column
merged_df = merged_df.drop(columns=['Date'])
merged_df

654

,date,hour,region,stop_count,eagles_home_game,eagles_away_game,76ers_home_game,76ers_away_game,phillies_home_game,phillies_away_game,...,TeamScore,OppScore,PointDiff,Win,Walkoff,Season,Streak,Rivalry,Mets,Braves
0,2014-01-01,0,4434_-6395,0,False,False,True,False,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2014-01-01,0,4434_-6394,0,False,False,True,False,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2014-01-01,0,4438_-6399,0,False,False,True,False,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2014-01-01,0,4435_-6398,0,False,False,True,False,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2014-01-01,0,4436_-6399,0,False,False,True,False,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15166651,2018-04-14,23,4427_-6392,0,False,False,False,False,True,False,...,9.0,4.0,5.0,1.0,0.0,2018.0,5.0,0.0,0.0,0.0
15166652,2018-04-14,23,4450_-6397,0,False,False,False,False,True,False,...,9.0,4.0,5.0,1.0,0.0,2018.0,5.0,0.0,0.0,0.0
15166653,2018-04-14,23,4449_-6396,0,False,False,False,False,True,False,...,9.0,4.0,5.0,1.0,0.0,2018.0,5.0,0.0,0.0,0.0
15166654,2018-04-14,23,4446_-6401,0,False,False,False,False,True,False,...,9.0,4.0,5.0,1.0,0.0,2018.0,5.0,0.0,0.0,0.0
15166655,2018-04-14,23,4445_-6401,0,False,False,False,False,True,False,...,9.0,4.0,5.0,1.0,0.0,2018.0,5.0,0.0,0.0,0.0

### Export full dataset

In [28]:
merged_df.to_csv('../data/phillies_all_days_aggregated_stops.csv')

## Add before/after column for gamedays

### Filter to just gamedays

In [29]:
gamedays = merged_df[merged_df['phillies_home_game'] == True].copy()

gamedays.drop(columns=game_cols, inplace=True)
gamedays

,date,hour,region,stop_count,Game,Day,StartTime,LOG,EndTime,DayGame,...,TeamScore,OppScore,PointDiff,Win,Walkoff,Season,Streak,Rivalry,Mets,Braves
858672,2014-03-31,0,4434_-6395,0,1.0,Monday,14:05:00,216.0,17:41:00,1.0,...,14.0,10.0,4.0,1.0,0.0,2014.0,1.0,0.0,0.0,0.0
858673,2014-03-31,0,4434_-6394,0,1.0,Monday,14:05:00,216.0,17:41:00,1.0,...,14.0,10.0,4.0,1.0,0.0,2014.0,1.0,0.0,0.0,0.0
858674,2014-03-31,0,4438_-6399,0,1.0,Monday,14:05:00,216.0,17:41:00,1.0,...,14.0,10.0,4.0,1.0,0.0,2014.0,1.0,0.0,0.0,0.0
858675,2014-03-31,0,4435_-6398,1,1.0,Monday,14:05:00,216.0,17:41:00,1.0,...,14.0,10.0,4.0,1.0,0.0,2014.0,1.0,0.0,0.0,0.0
858676,2014-03-31,0,4436_-6399,1,1.0,Monday,14:05:00,216.0,17:41:00,1.0,...,14.0,10.0,4.0,1.0,0.0,2014.0,1.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15166651,2018-04-14,23,4427_-6392,0,13.0,Saturday,18:10:00,166.0,20:56:00,0.0,...,9.0,4.0,5.0,1.0,0.0,2018.0,5.0,0.0,0.0,0.0
15166652,2018-04-14,23,4450_-6397,0,13.0,Saturday,18:10:00,166.0,20:56:00,0.0,...,9.0,4.0,5.0,1.0,0.0,2018.0,5.0,0.0,0.0,0.0
15166653,2018-04-14,23,4449_-6396,0,13.0,Saturday,18:10:00,166.0,20:56:00,0.0,...,9.0,4.0,5.0,1.0,0.0,2018.0,5.0,0.0,0.0,0.0
15166654,2018-04-14,23,4446_-6401,0,13.0,Saturday,18:10:00,166.0,20:56:00,0.0,...,9.0,4.0,5.0,1.0,0.0,2018.0,5.0,0.0,0.0,0.0
15166655,2018-04-14,23,4445_-6401,0,13.0,Saturday,18:10:00,166.0,20:56:00,0.0,...,9.0,4.0,5.0,1.0,0.0,2018.0,5.0,0.0,0.0,0.0

### Create start/end columns that are rounded to the nearest hour

In [30]:
gamedays['start_hour'] = (pd.to_datetime(gamedays['StartTime'], format='%H:%M:%S')
                          .dt.round('h') # round to the nearest hour
                          .dt.hour
                          )
gamedays['end_hour'] = (pd.to_datetime(gamedays['EndTime'], format='%H:%M:%S')
                        .dt.round('h') # round to the nearest hour
                        .dt.hour
                        )
gamedays

,date,hour,region,stop_count,Game,Day,StartTime,LOG,EndTime,DayGame,...,PointDiff,Win,Walkoff,Season,Streak,Rivalry,Mets,Braves,start_hour,end_hour
858672,2014-03-31,0,4434_-6395,0,1.0,Monday,14:05:00,216.0,17:41:00,1.0,...,4.0,1.0,0.0,2014.0,1.0,0.0,0.0,0.0,14,18
858673,2014-03-31,0,4434_-6394,0,1.0,Monday,14:05:00,216.0,17:41:00,1.0,...,4.0,1.0,0.0,2014.0,1.0,0.0,0.0,0.0,14,18
858674,2014-03-31,0,4438_-6399,0,1.0,Monday,14:05:00,216.0,17:41:00,1.0,...,4.0,1.0,0.0,2014.0,1.0,0.0,0.0,0.0,14,18
858675,2014-03-31,0,4435_-6398,1,1.0,Monday,14:05:00,216.0,17:41:00,1.0,...,4.0,1.0,0.0,2014.0,1.0,0.0,0.0,0.0,14,18
858676,2014-03-31,0,4436_-6399,1,1.0,Monday,14:05:00,216.0,17:41:00,1.0,...,4.0,1.0,0.0,2014.0,1.0,0.0,0.0,0.0,14,18
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15166651,2018-04-14,23,4427_-6392,0,13.0,Saturday,18:10:00,166.0,20:56:00,0.0,...,5.0,1.0,0.0,2018.0,5.0,0.0,0.0,0.0,18,21
15166652,2018-04-14,23,4450_-6397,0,13.0,Saturday,18:10:00,166.0,20:56:00,0.0,...,5.0,1.0,0.0,2018.0,5.0,0.0,0.0,0.0,18,21
15166653,2018-04-14,23,4449_-6396,0,13.0,Saturday,18:10:00,166.0,20:56:00,0.0,...,5.0,1.0,0.0,2018.0,5.0,0.0,0.0,0.0,18,21
15166654,2018-04-14,23,4446_-6401,0,13.0,Saturday,18:10:00,166.0,20:56:00,0.0,...,5.0,1.0,0.0,2018.0,5.0,0.0,0.0,0.0,18,21
15166655,2018-04-14,23,4445_-6401,0,13.0,Saturday,18:10:00,166.0,20:56:00,0.0,...,5.0,1.0,0.0,2018.0,5.0,0.0,0.0,0.0,18,21

### Classify each row as before/after/during the game

In [31]:
conditions = [
    gamedays['hour'] < gamedays['start_hour'],
    (gamedays['hour'] >= gamedays['start_hour']) & (gamedays['hour'] <= gamedays['end_hour']),
    gamedays['hour'] > gamedays['end_hour']
]

choices = ['before', 'during', 'after']

gamedays['game_period'] = np.select(conditions, choices, default="unknown")
gamedays

,date,hour,region,stop_count,Game,Day,StartTime,LOG,EndTime,DayGame,...,Win,Walkoff,Season,Streak,Rivalry,Mets,Braves,start_hour,end_hour,game_period
858672,2014-03-31,0,4434_-6395,0,1.0,Monday,14:05:00,216.0,17:41:00,1.0,...,1.0,0.0,2014.0,1.0,0.0,0.0,0.0,14,18,before
858673,2014-03-31,0,4434_-6394,0,1.0,Monday,14:05:00,216.0,17:41:00,1.0,...,1.0,0.0,2014.0,1.0,0.0,0.0,0.0,14,18,before
858674,2014-03-31,0,4438_-6399,0,1.0,Monday,14:05:00,216.0,17:41:00,1.0,...,1.0,0.0,2014.0,1.0,0.0,0.0,0.0,14,18,before
858675,2014-03-31,0,4435_-6398,1,1.0,Monday,14:05:00,216.0,17:41:00,1.0,...,1.0,0.0,2014.0,1.0,0.0,0.0,0.0,14,18,before
858676,2014-03-31,0,4436_-6399,1,1.0,Monday,14:05:00,216.0,17:41:00,1.0,...,1.0,0.0,2014.0,1.0,0.0,0.0,0.0,14,18,before
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15166651,2018-04-14,23,4427_-6392,0,13.0,Saturday,18:10:00,166.0,20:56:00,0.0,...,1.0,0.0,2018.0,5.0,0.0,0.0,0.0,18,21,after
15166652,2018-04-14,23,4450_-6397,0,13.0,Saturday,18:10:00,166.0,20:56:00,0.0,...,1.0,0.0,2018.0,5.0,0.0,0.0,0.0,18,21,after
15166653,2018-04-14,23,4449_-6396,0,13.0,Saturday,18:10:00,166.0,20:56:00,0.0,...,1.0,0.0,2018.0,5.0,0.0,0.0,0.0,18,21,after
15166654,2018-04-14,23,4446_-6401,0,13.0,Saturday,18:10:00,166.0,20:56:00,0.0,...,1.0,0.0,2018.0,5.0,0.0,0.0,0.0,18,21,after
15166655,2018-04-14,23,4445_-6401,0,13.0,Saturday,18:10:00,166.0,20:56:00,0.0,...,1.0,0.0,2018.0,5.0,0.0,0.0,0.0,18,21,after

In [32]:
# Check for any errors (missing values)
gamedays['game_period'].value_counts()

game_period
before    2381046
during     440592
after      371850
Name: count, dtype: int64

## Create km-based coordinates using region

In [33]:
gamedays[['lat', 'lng']] = gamedays['region'].str.split('_', expand=True)
gamedays

,date,hour,region,stop_count,Game,Day,StartTime,LOG,EndTime,DayGame,...,Season,Streak,Rivalry,Mets,Braves,start_hour,end_hour,game_period,lat,lng
858672,2014-03-31,0,4434_-6395,0,1.0,Monday,14:05:00,216.0,17:41:00,1.0,...,2014.0,1.0,0.0,0.0,0.0,14,18,before,4434,-6395
858673,2014-03-31,0,4434_-6394,0,1.0,Monday,14:05:00,216.0,17:41:00,1.0,...,2014.0,1.0,0.0,0.0,0.0,14,18,before,4434,-6394
858674,2014-03-31,0,4438_-6399,0,1.0,Monday,14:05:00,216.0,17:41:00,1.0,...,2014.0,1.0,0.0,0.0,0.0,14,18,before,4438,-6399
858675,2014-03-31,0,4435_-6398,1,1.0,Monday,14:05:00,216.0,17:41:00,1.0,...,2014.0,1.0,0.0,0.0,0.0,14,18,before,4435,-6398
858676,2014-03-31,0,4436_-6399,1,1.0,Monday,14:05:00,216.0,17:41:00,1.0,...,2014.0,1.0,0.0,0.0,0.0,14,18,before,4436,-6399
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15166651,2018-04-14,23,4427_-6392,0,13.0,Saturday,18:10:00,166.0,20:56:00,0.0,...,2018.0,5.0,0.0,0.0,0.0,18,21,after,4427,-6392
15166652,2018-04-14,23,4450_-6397,0,13.0,Saturday,18:10:00,166.0,20:56:00,0.0,...,2018.0,5.0,0.0,0.0,0.0,18,21,after,4450,-6397
15166653,2018-04-14,23,4449_-6396,0,13.0,Saturday,18:10:00,166.0,20:56:00,0.0,...,2018.0,5.0,0.0,0.0,0.0,18,21,after,4449,-6396
15166654,2018-04-14,23,4446_-6401,0,13.0,Saturday,18:10:00,166.0,20:56:00,0.0,...,2018.0,5.0,0.0,0.0,0.0,18,21,after,4446,-6401
15166655,2018-04-14,23,4445_-6401,0,13.0,Saturday,18:10:00,166.0,20:56:00,0.0,...,2018.0,5.0,0.0,0.0,0.0,18,21,after,4445,-6401

## Clean and Export final dataset

### Drop unnecessary columns here (Feel free to add more!)

In [34]:
final_df = gamedays.copy()
final_df.to_csv('../data/phillies_square_modeling_df.csv')