In [1]:
import pandas as pd

In [6]:
philly_stops = pd.read_csv("philly_stops.csv")

/tmp/ipykernel_155/4163258799.py:1: DtypeWarning: Columns (7,12,15,16,17,18,20,21) have mixed types. Specify dtype option on import or set low_memory=False.
  philly_stops = pd.read_csv("philly_stops.csv")

In [7]:
philly_stops.head()

,raw_row_number,date,time,location,lat,lng,district,service_area,subject_age,subject_race,...,arrest_made,outcome,contraband_found,frisk_performed,search_conducted,search_person,search_vehicle,raw_race,raw_individual_contraband,raw_vehicle_contraband
0,411981,2014-01-01,4440.0,NaN,NaN,NaN,19.0,191,31.0,black,...,True,arrest,True,False,True,True,False,Black - Non-Latino,True,False
1,407442,2014-01-01,7020.0,NaN,NaN,NaN,12.0,121,21.0,black,...,True,arrest,False,True,True,True,False,Black - Non-Latino,False,False
2,217556,2014-01-01,12600.0,3400 BLOCK SPRUCE ST,39.950424,-75.192680,18.0,183,24.0,black,...,False,NaN,NaN,False,False,False,False,Black - Non-Latino,False,False
3,217557,2014-01-01,13200.0,3400 BLOCK SPRUCE ST,39.950424,-75.192680,18.0,183,20.0,black,...,False,NaN,NaN,False,False,False,False,Black - Non-Latino,False,False
4,230988,2014-01-01,30600.0,N 56TH ST / UPLAND WAY,39.983712,-75.234188,19.0,193,31.0,black,...,False,NaN,NaN,False,False,False,False,Black - Non-Latino,False,False

In [9]:
eagles = pd.read_csv("cleanedEaglesData.csv")

In [10]:
eagles.columns

Index(['Game', 'Day', 'Date', 'StartTime', 'xEndTime', 'Home', 'Opp',
       'TeamScore', 'OppScore', 'PointDiff', 'DefTO', 'OffTO', 'TODiff', 'Win',
       'OT', 'Season', 'Wins', 'Losses', 'Streak', 'Rivalry', 'Giants',
       'Cowboys', 'RegularSeason', 'Division', 'ConfChamp', 'SuperBowl'],
      dtype='object')

In [11]:
philly_stops.columns

Index(['raw_row_number', 'date', 'time', 'location', 'lat', 'lng', 'district',
       'service_area', 'subject_age', 'subject_race', 'subject_sex', 'type',
       'arrest_made', 'outcome', 'contraband_found', 'frisk_performed',
       'search_conducted', 'search_person', 'search_vehicle', 'raw_race',
       'raw_individual_contraband', 'raw_vehicle_contraband'],
      dtype='object')

In [13]:
philly_stops['date'] = pd.to_datetime(philly_stops['date'], format='mixed', errors='coerce').dt.date

In [14]:
eagles['Date'] = pd.to_datetime(eagles['Date']).dt.date

In [16]:
philly_stops = philly_stops.dropna(subset=['date'])

In [17]:
eagles_home_games = eagles.loc[eagles['Home'] == 1, 'Date'].unique()

In [18]:
philly_stops['date'].head()

0    2014-01-01
1    2014-01-01
2    2014-01-01
3    2014-01-01
4    2014-01-01
Name: date, dtype: object

In [19]:
# all eagles home game dates
eagles_home_games = eagles.loc[eagles['Home'] == 1, 'Date'].unique()

# new col to philly_stops that flags home game days
philly_stops['EaglesHomeGame'] = philly_stops['date'].isin(eagles_home_games).astype(int)

In [20]:
philly_stops[['date', 'EaglesHomeGame']].head(10)

         date  EaglesHomeGame
0  2014-01-01               0
1  2014-01-01               0
2  2014-01-01               0
3  2014-01-01               0
4  2014-01-01               0
5  2014-01-01               0
6  2014-01-01               0
7  2014-01-01               0
8  2014-01-01               0
9  2014-01-01               0

In [21]:
# traffic stops --> eagle home days
philly_stops_eagles = philly_stops[philly_stops['EaglesHomeGame'] == 1].copy()

In [22]:
len(philly_stops_eagles)

6304

In [23]:
philly_stops_eagles.head()

,raw_row_number,date,time,location,lat,lng,district,service_area,subject_age,subject_race,...,outcome,contraband_found,frisk_performed,search_conducted,search_person,search_vehicle,raw_race,raw_individual_contraband,raw_vehicle_contraband,EaglesHomeGame
276772,216366,2014-09-15,0.0,1200 BLOCK S 26TH ST,39.938690,-75.186919,17.0,172,32.0,black,...,NaN,NaN,False,False,False,False,Black - Non-Latino,False,False,1
276773,320076,2014-09-15,0.0,2600 BLOCK N FRONT ST,39.989349,-75.131270,26.0,261,24.0,white,...,NaN,NaN,False,False,False,False,White - Non-Latino,False,False,1
276774,205399,2014-09-15,0.0,4400 BLOCK FRANKFORD AV,40.012579,-75.087572,15.0,151,38.0,white,...,NaN,NaN,False,False,False,False,White - Non-Latino,False,False,1
276775,111643,2014-09-15,0.0,7100 BLOCK CASTOR AV,40.048152,-75.069087,2.0,023,24.0,black,...,NaN,NaN,False,False,False,False,Black - Non-Latino,False,False,1
276776,295845,2014-09-15,60.0,N 63RD ST / MASTER ST,39.972184,-75.244937,19.0,192,28.0,black,...,NaN,NaN,False,False,False,False,Black - Non-Latino,False,False,1