# Eagles x SOPP Data Wrangling (square regions)

In [1]:
import pandas as pd
import numpy as np
import folium

## Import Data Sets

In [2]:
philly_stops = pd.read_csv("../data/pa_philadelphia_2020_04_01.csv")

/var/folders/k9/6ttfwb0s7ssb63rlmgdbybc80000gn/T/ipykernel_26996/1703290750.py:1: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  philly_stops = pd.read_csv("../data/pa_philadelphia_2020_04_01.csv")

In [3]:
philly_stops

,raw_row_number,date,time,location,lat,lng,district,service_area,subject_age,subject_race,...,arrest_made,outcome,contraband_found,frisk_performed,search_conducted,search_person,search_vehicle,raw_race,raw_individual_contraband,raw_vehicle_contraband
0,411981,2014-01-01,01:14:00,NaN,NaN,NaN,19.0,191,31.0,black,...,True,arrest,True,False,True,True,False,Black - Non-Latino,True,False
1,407442,2014-01-01,01:57:00,NaN,NaN,NaN,12.0,121,21.0,black,...,True,arrest,False,True,True,True,False,Black - Non-Latino,False,False
2,217556,2014-01-01,03:30:00,3400 BLOCK SPRUCE ST,39.950424,-75.192680,18.0,183,24.0,black,...,False,NaN,NaN,False,False,False,False,Black - Non-Latino,False,False
3,217557,2014-01-01,03:40:00,3400 BLOCK SPRUCE ST,39.950424,-75.192680,18.0,183,20.0,black,...,False,NaN,NaN,False,False,False,False,Black - Non-Latino,False,False
4,230988,2014-01-01,08:30:00,N 56TH ST / UPLAND WAY,39.983712,-75.234188,19.0,193,31.0,black,...,False,NaN,NaN,False,False,False,False,Black - Non-Latino,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1865091,1791698,2018-04-14,21:36:00,S 59TH ST / ELMWOOD AV,39.928084,-75.221956,12.0,123,60.0,black,...,False,NaN,NaN,False,False,False,False,Black - Non-Latino,False,False
1865092,1789312,2018-04-14,22:01:00,2600 BLOCK JUDSON ST,39.998242,-75.175190,39.0,393,33.0,asian/pacific islander,...,False,NaN,NaN,False,False,False,False,Asian,False,False
1865093,1791237,2018-04-14,22:48:00,500 BLOCK E OLNEY AV,40.033812,-75.114429,35.0,352,21.0,black,...,True,arrest,False,True,True,True,False,Black - Non-Latino,False,False
1865094,1791243,2018-04-14,22:48:00,500 BLOCK E OLNEY AV,40.033812,-75.114429,35.0,352,22.0,black,...,True,arrest,False,True,True,True,False,Black - Non-Latino,False,False
1865095,1791232,2018-04-14,23:10:00,200 BLOCK W LEHIGH AV,39.991461,-75.134880,25.0,253,69.0,black,...,False,NaN,NaN,False,False,False,False,Black - Non-Latino,False,False

In [4]:
eagles = pd.read_csv("../data/cleanedEaglesData.csv")
eagles

,Game,Day,Date,StartTime,xEndTime,Home,Opp,TeamScore,OppScore,PointDiff,...,Wins,Losses,Streak,Rivalry,Giants,Cowboys,RegularSeason,Division,ConfChamp,SuperBowl
0,1,Sunday,2014-09-07,13:02:00,16:14:00,0,Jacksonville Jaguars,34,17,17,...,1,0,1,0,0,0,1,0,0,0
1,2,Monday,2014-09-15,20:31:00,23:43:00,1,Indianapolis Colts,30,27,3,...,2,0,2,0,0,0,1,0,0,0
2,3,Sunday,2014-09-21,13:02:00,16:14:00,0,Washington Redskins,37,34,3,...,3,0,3,0,0,0,1,0,0,0
3,4,Sunday,2014-09-28,16:25:00,19:37:00,1,San Francisco 49ers,21,26,-5,...,3,1,-1,0,0,0,1,0,0,0
4,5,Sunday,2014-10-05,13:02:00,16:14:00,0,St. Louis Rams,34,28,6,...,4,1,1,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62,16,Monday,2017-12-25,20:30:00,23:42:00,0,Oakland Raiders,19,10,9,...,13,2,3,0,0,0,1,0,0,0
63,17,Sunday,2017-12-31,13:00:00,16:12:00,0,Dallas Cowboys,0,6,-6,...,13,3,-1,1,0,1,1,0,0,0
64,Division,Saturday,2018-01-13,16:35:00,19:47:00,0,Atlanta Falcons,15,10,5,...,14,3,1,0,0,0,0,1,0,0
65,Conf. Champ.,Sunday,2018-01-21,18:40:00,21:52:00,0,Minnesota Vikings,38,7,31,...,15,3,2,0,0,0,0,0,1,0
66,SuperBowl,Sunday,2018-02-04,18:30:00,21:42:00,0,New England Patriots,41,33,8,...,16,3,3,0,0,0,0,0,0,1

In [5]:
eagles.columns

Index(['Game', 'Day', 'Date', 'StartTime', 'xEndTime', 'Home', 'Opp',
       'TeamScore', 'OppScore', 'PointDiff', 'DefTO', 'OffTO', 'TODiff', 'Win',
       'OT', 'Season', 'Wins', 'Losses', 'Streak', 'Rivalry', 'Giants',
       'Cowboys', 'RegularSeason', 'Division', 'ConfChamp', 'SuperBowl'],
      dtype='object')

In [6]:
philly_stops.columns

Index(['raw_row_number', 'date', 'time', 'location', 'lat', 'lng', 'district',
       'service_area', 'subject_age', 'subject_race', 'subject_sex', 'type',
       'arrest_made', 'outcome', 'contraband_found', 'frisk_performed',
       'search_conducted', 'search_person', 'search_vehicle', 'raw_race',
       'raw_individual_contraband', 'raw_vehicle_contraband'],
      dtype='object')

## Parse Date columns

In [7]:
philly_stops['date'] = pd.to_datetime(philly_stops['date'], format='mixed', errors='coerce').dt.date

In [8]:
eagles['Date'] = pd.to_datetime(eagles['Date']).dt.date

In [9]:
philly_stops = philly_stops.dropna(subset=['date'])

In [10]:
philly_stops['date'].head()

0    2014-01-01
1    2014-01-01
2    2014-01-01
3    2014-01-01
4    2014-01-01
Name: date, dtype: object

## Create square regions

### Drop unnecessary columns

In [11]:
philly_stops = philly_stops.iloc[:, [1, 2, 4, 5]]
philly_stops.columns

Index(['date', 'time', 'lat', 'lng'], dtype='object')

### Remove NA value rows

In [12]:
# Check % of na values first
philly_stops.isna().mean() * 100

philly_stops = philly_stops.dropna()
philly_stops

               date      time        lat        lng
2        2014-01-01  03:30:00  39.950424 -75.192680
3        2014-01-01  03:40:00  39.950424 -75.192680
4        2014-01-01  08:30:00  39.983712 -75.234188
5        2014-01-01  08:53:00  39.953124 -75.181936
6        2014-01-01  09:00:00  39.989757 -75.229019
...             ...       ...        ...        ...
1865091  2018-04-14  21:36:00  39.928084 -75.221956
1865092  2018-04-14  22:01:00  39.998242 -75.175190
1865093  2018-04-14  22:48:00  40.033812 -75.114429
1865094  2018-04-14  22:48:00  40.033812 -75.114429
1865095  2018-04-14  23:10:00  39.991461 -75.134880

[1760399 rows x 4 columns]

### Convert latitude and longitude to Km based coordinates and create 1 km square grid

In [13]:
km_to_deg_lat = 1 / 111
mean_lat = philly_stops['lat'].mean()

# Longitude conversion depends on latitude
km_to_deg_lng = 1 / (111 * np.cos(np.radians(mean_lat)))

# Bin each point the floor km
philly_stops['lat_bin'] = np.floor(philly_stops['lat'] / km_to_deg_lat)
philly_stops['lng_bin'] = np.floor(philly_stops['lng'] / km_to_deg_lng)

# Create a region ID
philly_stops['region'] = philly_stops['lat_bin'].astype(int).astype(str) + "_" + philly_stops['lng_bin'].astype(int).astype(str)

print(philly_stops[['lat', 'lng', 'region']].head())

         lat        lng      region
2  39.950424 -75.192680  4434_-6395
3  39.950424 -75.192680  4434_-6395
4  39.983712 -75.234188  4438_-6399
5  39.953124 -75.181936  4434_-6394
6  39.989757 -75.229019  4438_-6398

In [14]:
print(km_to_deg_lng)

0.011758845009850643

### Plot grid on a map

In [15]:
# Center map
center_lat = philly_stops['lat'].mean()
center_lng = philly_stops['lng'].mean()

m = folium.Map(location=[center_lat, center_lng], zoom_start=11)

# Get unique grid cells
unique_cells = philly_stops[['lat_bin', 'lng_bin']].drop_duplicates()

for _, row in unique_cells.iterrows():
    lat_bin = row['lat_bin']
    lng_bin = row['lng_bin']

    # Convert back to coordinates (bottom-left corner)
    lat_min = lat_bin * km_to_deg_lat
    lng_min = lng_bin * km_to_deg_lng

    lat_max = lat_min + km_to_deg_lat
    lng_max = lng_min + km_to_deg_lng

    # Draw rectangle
    folium.Rectangle(
        bounds=[[lat_min, lng_min], [lat_max, lng_max]],
        color='blue',
        weight=1,
        fill=False
    ).add_to(m)

# Optional: plot some points
# for _, row in philly_stops.sample(10000).iterrows():  # sample for performance
#     folium.CircleMarker(
#         location=[row['lat'], row['lng']],
#         radius=.2,
#         color='red',
#         fill=True
#     ).add_to(m)

m

In [16]:
philly_stops

,date,time,lat,lng,lat_bin,lng_bin,region
2,2014-01-01,03:30:00,39.950424,-75.192680,4434.0,-6395.0,4434_-6395
3,2014-01-01,03:40:00,39.950424,-75.192680,4434.0,-6395.0,4434_-6395
4,2014-01-01,08:30:00,39.983712,-75.234188,4438.0,-6399.0,4438_-6399
5,2014-01-01,08:53:00,39.953124,-75.181936,4434.0,-6394.0,4434_-6394
6,2014-01-01,09:00:00,39.989757,-75.229019,4438.0,-6398.0,4438_-6398
...,...,...,...,...,...,...,...
1865091,2018-04-14,21:36:00,39.928084,-75.221956,4432.0,-6398.0,4432_-6398
1865092,2018-04-14,22:01:00,39.998242,-75.175190,4439.0,-6394.0,4439_-6394
1865093,2018-04-14,22:48:00,40.033812,-75.114429,4443.0,-6388.0,4443_-6388
1865094,2018-04-14,22:48:00,40.033812,-75.114429,4443.0,-6388.0,4443_-6388
1865095,2018-04-14,23:10:00,39.991461,-75.134880,4439.0,-6390.0,4439_-6390

### Drop extra location columns

In [17]:
philly_stops.drop(columns=['lat', 'lng', 'lat_bin', 'lng_bin'], inplace=True)
philly_stops

               date      time      region
2        2014-01-01  03:30:00  4434_-6395
3        2014-01-01  03:40:00  4434_-6395
4        2014-01-01  08:30:00  4438_-6399
5        2014-01-01  08:53:00  4434_-6394
6        2014-01-01  09:00:00  4438_-6398
...             ...       ...         ...
1865091  2018-04-14  21:36:00  4432_-6398
1865092  2018-04-14  22:01:00  4439_-6394
1865093  2018-04-14  22:48:00  4443_-6388
1865094  2018-04-14  22:48:00  4443_-6388
1865095  2018-04-14  23:10:00  4439_-6390

[1760399 rows x 3 columns]

## Aggregate stops by date, region, and hour

### Convert time to hour block

In [18]:
philly_stops['hour'] = pd.to_datetime(philly_stops['time'], format='%H:%M:%S').dt.hour
philly_stops.head()

         date      time      region  hour
2  2014-01-01  03:30:00  4434_-6395     3
3  2014-01-01  03:40:00  4434_-6395     3
4  2014-01-01  08:30:00  4438_-6399     8
5  2014-01-01  08:53:00  4434_-6394     8
6  2014-01-01  09:00:00  4438_-6398     9

In [19]:
# Drop time column
philly_stops.drop(columns=['time'], inplace=True)
philly_stops.head()

         date      region  hour
2  2014-01-01  4434_-6395     3
3  2014-01-01  4434_-6395     3
4  2014-01-01  4438_-6399     8
5  2014-01-01  4434_-6394     8
6  2014-01-01  4438_-6398     9

### Aggregate (count) the number of stops for each date, region, hour combination

In [20]:
aggregate_philly_stops = (
    philly_stops
    .groupby(['date', 'hour', 'region'])
    .size()
    .reset_index(name='stop_count')
)

aggregate_philly_stops

               date  hour      region  stop_count
0        2014-01-01     3  4434_-6395           2
1        2014-01-01     8  4434_-6394           1
2        2014-01-01     8  4438_-6399           1
3        2014-01-01     9  4435_-6398           1
4        2014-01-01     9  4436_-6399           1
...             ...   ...         ...         ...
1087112  2018-04-14    21  4446_-6393           1
1087113  2018-04-14    21  4446_-6394           1
1087114  2018-04-14    22  4439_-6394           1
1087115  2018-04-14    22  4443_-6388           2
1087116  2018-04-14    23  4439_-6390           1

[1087117 rows x 4 columns]

## Fill 0 stops for any missing combinations

In [21]:
# Create full date range
all_dates = pd.date_range(start=aggregate_philly_stops['date'].min(), end=aggregate_philly_stops['date'].max(), freq='D')

# Define full hour range (0-23)
all_hours = range(0, 24)

# Get all regions
all_regions = aggregate_philly_stops['region'].unique()

# Create full combination grid
full_index = pd.MultiIndex.from_product(
    [all_dates, all_hours, all_regions],
    names=['date', 'hour', 'region']
)

# Reindex
aggregate_philly_stops = (
    aggregate_philly_stops.set_index(['date', 'hour', 'region'])
      .reindex(full_index)
      .reset_index()
)

# Fill missing values with 0 stops
aggregate_philly_stops['stop_count'] = aggregate_philly_stops['stop_count'].fillna(0).astype(int)
aggregate_philly_stops['date'] = pd.to_datetime(aggregate_philly_stops['date']).dt.date
aggregate_philly_stops

                date  hour      region  stop_count
0         2014-01-01     0  4434_-6395           0
1         2014-01-01     0  4434_-6394           0
2         2014-01-01     0  4438_-6399           0
3         2014-01-01     0  4435_-6398           0
4         2014-01-01     0  4436_-6399           0
...              ...   ...         ...         ...
15099115  2018-04-14    23  4427_-6392           0
15099116  2018-04-14    23  4450_-6397           0
15099117  2018-04-14    23  4449_-6396           0
15099118  2018-04-14    23  4446_-6401           0
15099119  2018-04-14    23  4445_-6401           0

[15099120 rows x 4 columns]

### Calculate Expected number of rows for verification

In [22]:
len(all_dates)*len(all_hours)*len(all_regions)

15099120

## Add game information and home game flag to stop data

### First, check that all gamedays are in the stop data

In [23]:
missing_dates = eagles.loc[~eagles['Date'].isin(aggregate_philly_stops['date']), 'Date']

# Print any dates that are missing from the stop data
missing_dates

Series([], Name: Date, dtype: object)

 ### Left join philly stops with Eagles data

In [24]:
# Merge (left join keeps all philly_stops rows)
# non-gamedays will have NA in all Eagles columns
merged_df = aggregate_philly_stops.merge(
    eagles,
    how='left',
    left_on='date',
    right_on='Date'
)

In [25]:
# Check that all gamedays are in the final dataset.
merged_df['Date'].nunique()

67

### Create gameday indicator column

In [26]:
# Create gameday indicator (1 if matched with Eagles game, else 0)
merged_df['gameday'] = merged_df['Date'].notna().astype(int)

# Drop the Eagles date column
merged_df = merged_df.drop(columns=['Date'])
merged_df

,date,hour,region,stop_count,Game,Day,StartTime,xEndTime,Home,Opp,...,Losses,Streak,Rivalry,Giants,Cowboys,RegularSeason,Division,ConfChamp,SuperBowl,gameday
0,2014-01-01,0,4434_-6395,0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
1,2014-01-01,0,4434_-6394,0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
2,2014-01-01,0,4438_-6399,0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
3,2014-01-01,0,4435_-6398,0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
4,2014-01-01,0,4436_-6399,0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15099115,2018-04-14,23,4427_-6392,0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
15099116,2018-04-14,23,4450_-6397,0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
15099117,2018-04-14,23,4449_-6396,0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
15099118,2018-04-14,23,4446_-6401,0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
15099119,2018-04-14,23,4445_-6401,0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0

### Export full dataset

In [28]:
merged_df.to_csv('../data/all_days_aggregated_stops.csv')

## Add before/after column for gamedays

### Filter to just gamedays

In [27]:
gamedays = merged_df[merged_df['gameday'] == 1].copy()
gamedays

,date,hour,region,stop_count,Game,Day,StartTime,xEndTime,Home,Opp,...,Losses,Streak,Rivalry,Giants,Cowboys,RegularSeason,Division,ConfChamp,SuperBowl,gameday
2402352,2014-09-07,0,4434_-6395,0,1,Sunday,13:02:00,16:14:00,0.0,Jacksonville Jaguars,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1
2402353,2014-09-07,0,4434_-6394,0,1,Sunday,13:02:00,16:14:00,0.0,Jacksonville Jaguars,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1
2402354,2014-09-07,0,4438_-6399,0,1,Sunday,13:02:00,16:14:00,0.0,Jacksonville Jaguars,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1
2402355,2014-09-07,0,4435_-6398,4,1,Sunday,13:02:00,16:14:00,0.0,Jacksonville Jaguars,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1
2402356,2014-09-07,0,4436_-6399,0,1,Sunday,13:02:00,16:14:00,0.0,Jacksonville Jaguars,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14433403,2018-02-04,23,4427_-6392,0,SuperBowl,Sunday,18:30:00,21:42:00,0.0,New England Patriots,...,3.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1
14433404,2018-02-04,23,4450_-6397,0,SuperBowl,Sunday,18:30:00,21:42:00,0.0,New England Patriots,...,3.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1
14433405,2018-02-04,23,4449_-6396,0,SuperBowl,Sunday,18:30:00,21:42:00,0.0,New England Patriots,...,3.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1
14433406,2018-02-04,23,4446_-6401,0,SuperBowl,Sunday,18:30:00,21:42:00,0.0,New England Patriots,...,3.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1
14433407,2018-02-04,23,4445_-6401,0,SuperBowl,Sunday,18:30:00,21:42:00,0.0,New England Patriots,...,3.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1

### Create start/end columns that are rounded to the nearest hour

In [28]:
gamedays['start_hour'] = (pd.to_datetime(gamedays['StartTime'], format='%H:%M:%S')
                          .dt.round('h') # round to the nearest hour
                          .dt.hour
                          )
gamedays['end_hour'] = (pd.to_datetime(gamedays['xEndTime'], format='%H:%M:%S')
                        .dt.round('h') # round to the nearest hour
                        .dt.hour
                        )
gamedays

,date,hour,region,stop_count,Game,Day,StartTime,xEndTime,Home,Opp,...,Rivalry,Giants,Cowboys,RegularSeason,Division,ConfChamp,SuperBowl,gameday,start_hour,end_hour
2402352,2014-09-07,0,4434_-6395,0,1,Sunday,13:02:00,16:14:00,0.0,Jacksonville Jaguars,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1,13,16
2402353,2014-09-07,0,4434_-6394,0,1,Sunday,13:02:00,16:14:00,0.0,Jacksonville Jaguars,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1,13,16
2402354,2014-09-07,0,4438_-6399,0,1,Sunday,13:02:00,16:14:00,0.0,Jacksonville Jaguars,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1,13,16
2402355,2014-09-07,0,4435_-6398,4,1,Sunday,13:02:00,16:14:00,0.0,Jacksonville Jaguars,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1,13,16
2402356,2014-09-07,0,4436_-6399,0,1,Sunday,13:02:00,16:14:00,0.0,Jacksonville Jaguars,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1,13,16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14433403,2018-02-04,23,4427_-6392,0,SuperBowl,Sunday,18:30:00,21:42:00,0.0,New England Patriots,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1,18,22
14433404,2018-02-04,23,4450_-6397,0,SuperBowl,Sunday,18:30:00,21:42:00,0.0,New England Patriots,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1,18,22
14433405,2018-02-04,23,4449_-6396,0,SuperBowl,Sunday,18:30:00,21:42:00,0.0,New England Patriots,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1,18,22
14433406,2018-02-04,23,4446_-6401,0,SuperBowl,Sunday,18:30:00,21:42:00,0.0,New England Patriots,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1,18,22
14433407,2018-02-04,23,4445_-6401,0,SuperBowl,Sunday,18:30:00,21:42:00,0.0,New England Patriots,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1,18,22

### Classify each row as before/after/during the game

In [29]:
conditions = [
    gamedays['hour'] < gamedays['start_hour'],
    (gamedays['hour'] >= gamedays['start_hour']) & (gamedays['hour'] <= gamedays['end_hour']),
    gamedays['hour'] > gamedays['end_hour']
]

choices = ['before', 'during', 'after']

gamedays['game_period'] = np.select(conditions, choices, default="unknown")
gamedays

,date,hour,region,stop_count,Game,Day,StartTime,xEndTime,Home,Opp,...,Giants,Cowboys,RegularSeason,Division,ConfChamp,SuperBowl,gameday,start_hour,end_hour,game_period
2402352,2014-09-07,0,4434_-6395,0,1,Sunday,13:02:00,16:14:00,0.0,Jacksonville Jaguars,...,0.0,0.0,1.0,0.0,0.0,0.0,1,13,16,before
2402353,2014-09-07,0,4434_-6394,0,1,Sunday,13:02:00,16:14:00,0.0,Jacksonville Jaguars,...,0.0,0.0,1.0,0.0,0.0,0.0,1,13,16,before
2402354,2014-09-07,0,4438_-6399,0,1,Sunday,13:02:00,16:14:00,0.0,Jacksonville Jaguars,...,0.0,0.0,1.0,0.0,0.0,0.0,1,13,16,before
2402355,2014-09-07,0,4435_-6398,4,1,Sunday,13:02:00,16:14:00,0.0,Jacksonville Jaguars,...,0.0,0.0,1.0,0.0,0.0,0.0,1,13,16,before
2402356,2014-09-07,0,4436_-6399,0,1,Sunday,13:02:00,16:14:00,0.0,Jacksonville Jaguars,...,0.0,0.0,1.0,0.0,0.0,0.0,1,13,16,before
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14433403,2018-02-04,23,4427_-6392,0,SuperBowl,Sunday,18:30:00,21:42:00,0.0,New England Patriots,...,0.0,0.0,0.0,0.0,0.0,1.0,1,18,22,after
14433404,2018-02-04,23,4450_-6397,0,SuperBowl,Sunday,18:30:00,21:42:00,0.0,New England Patriots,...,0.0,0.0,0.0,0.0,0.0,1.0,1,18,22,after
14433405,2018-02-04,23,4449_-6396,0,SuperBowl,Sunday,18:30:00,21:42:00,0.0,New England Patriots,...,0.0,0.0,0.0,0.0,0.0,1.0,1,18,22,after
14433406,2018-02-04,23,4446_-6401,0,SuperBowl,Sunday,18:30:00,21:42:00,0.0,New England Patriots,...,0.0,0.0,0.0,0.0,0.0,1.0,1,18,22,after
14433407,2018-02-04,23,4445_-6401,0,SuperBowl,Sunday,18:30:00,21:42:00,0.0,New England Patriots,...,0.0,0.0,0.0,0.0,0.0,1.0,1,18,22,after

In [30]:
# Check for any errors (missing values)
gamedays['game_period'].value_counts()

game_period
before    427326
after     136278
during     82812
Name: count, dtype: int64

## Clean and Export final dataset

### Drop unnecessary columns here (Feel free to add more!)

In [32]:
final_df = gamedays.copy()
final_df.to_csv('../data/eagles_square_modeling_df.csv')